#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Arduino state=floating
bspc rule -a discord desktop='^9' follow=off focus=off
bspc rule -a Brave-browser desktop='^1' follow=on focus=on
bspc rule -a Emacs desktop='^3' state=fullscreen follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop='^4' follow=on focus=on
bspc rule -a Shutter state=floating


# Border
bspc config focused_border_color        "#6bf5ff"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#07f642"

#
# Autostart
# Emacs
emacs &
# Discord
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
# Internet browser
brave &
# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# Set keyboard
setxkbmap -model pc105 -layout us,pt -variant dvorak-alt-intl, -option grp:win_space_toggle,
