vim.cmd("colo gruvbox")
--vim.cmd(" let g:vimtex_view_method = 'zathura'")
--vim.cmd("let g:UltiSnipsExpandTrigger='<tab>'")
--vim.cmd("let g:UltiSnipsJumpForwardTrigger='<tab>'")
--vim.cmd("let g:UltiSnipsJumpBackwardTrigger='<s-tab>'")
--vim.cmd("autocmd FileType tex inoremap <buffer> <C-\> \(")
--vim.cmd("autocmd FileType tex inoremap <buffer> <A-[> \[")

require('config')
require('mappings')
